class ShoppingItem {
  static List<String> fruits = [
    "apple",
    "apricot",
    "avocado",
    "banana",
    "bell pepper",
    "bilberry",
    "blackberry",
    "blackcurrant",
    "blood orange",
    "blueberry",
    "boysenberry",
    "breadfruit",
    "canary melon",
    "cantaloupe",
    "cherimoya",
    "cherry",
    "chili pepper",
    "clementine",
    "cloudberry",
    "coconut",
    "cranberry",
    "cucumber",
    "currant",
    "damson",
    "date",
    "dragonfruit",
    "durian",
    "eggplant",
    "elderberry",
    "feijoa",
    "fig",
    "goji berry",
    "gooseberry",
    "grape",
    "grapefruit",
    "guava",
    "honeydew",
    "huckleberry",
    "jackfruit",
    "jambul",
    "jujube",
    "kiwi fruit",
    "kumquat",
    "lemon",
    "lime",
    "loquat",
    "lychee",
    "mandarine",
    "mango",
    "mulberry",
    "nectarine",
    "nut",
    "olive",
    "orange",
    "pamelo",
    "papaya",
    "passionfruit",
    "peach",
    "pear",
    "persimmon",
    "physalis",
    "pineapple",
    "plum",
    "pomegranate",
    "pomelo",
    "purple mangosteen",
    "quince",
    "raisin",
    "rambutan",
    "raspberry",
    "redcurrant",
    "rock melon",
    "salal berry",
    "satsuma",
    "star fruit",
    "strawberry",
    "tamarillo",
    "tangerine",
    "tomato",
    "ugli fruit",
    "watermelon"
  ];

  static List<String> herbs = [
    "Angelica",
    "Basil",
    "Holy Basil",
    "Thai Basil",
    "Bay leaf",
    "Indian Bay leaf",
    "Boldo",
    "Borage",
    "Chervil",
    "Chives",
    "Garlic Chives",
    "Cicely",
    "Coriander leaf",
    "Cilantro",
    "Bolivian Coriander",
    "Vietnamese Coriander",
    "Culantro",
    "Cress",
    "Curry leaf",
    "Dill",
    "Epazote",
    "Hemp",
    "Hoja santa",
    "Houttuynia cordata",
    "Hyssop",
    "Jimbu",
    "Kinh gioi",
    "Lavender",
    "Lemon balm",
    "Lemon grass",
    "Lemon myrtle",
    "Lemon verbena",
    "Limnophila aromatica",
    "Lovage",
    "Marjoram",
    "Mint",
    "Mugwort",
    "Mitsuba",
    "Oregano",
    "Parsley",
    "Perilla",
    "Rosemary",
    "Rue",
    "Sage",
    "Savory",
    "Sansho",
    "Shiso",
    "Sorrel",
    "Tarragon",
    "Thyme",
    "Woodruff"
  ];

  static List<String> spicies = [
    "Aonori",
    "Ajwain",
    "Allspice",
    "Amchoor",
    "Anise",
    "Star Anise",
    "Asafoetida",
    "Camphor",
    "Caraway",
    "Cardamom",
    "Black Cardamom",
    "Cassia",
    "Celery powder",
    "Celery seed",
    "Charoli",
    "Chenpi",
    "Cinnamon",
    "Clove",
    "Coriander seed",
    "Cubeb",
    "Cumin",
    "Nigella sativa",
    "Bunium persicum",
    "Dill",
    "Dill seed",
    "Fennel",
    "Fenugreek",
    "Fingerroot",
    "Greater Galangal",
    "Lesser Galangal",
    "Garlic",
    "Ginger",
    "Aromatic Ginger",
    "Golpar",
    "Grains of Paradise",
    "Grains of Selim",
    "Horseradish",
    "Juniper berry",
    "Kokum",
    "Korarima",
    "Dried Lime",
    "Liquorice",
    "Litsea cubeba",
    "Mace",
    "Mango-ginger",
    "Mastic",
    "Mahlab",
    "Black Mustard",
    "Brown Mustard",
    "White Mustard",
    "Nigella",
    "Njangsa",
    "Nutmeg",
    "Alligator Pepper",
    "Brazilian Pepper",
    "Chili Pepper",
    "Cayenne pepper",
    "Paprika",
    "Long Pepper",
    "Peruvian Pepper",
    "East Asian Pepper",
    "Sichuan Pepper",
    "Sansho",
    "Tasmanian Pepper",
    "Black Peppercorn",
    "Green Peppercorn",
    "White Peppercorn",
    "Pomegranate seed",
    "Poppy seed",
    "Radhuni",
    "Rose",
    "Saffron",
    "Salt",
    "Sarsaparilla",
    "Sassafras",
    "Sesame",
    "Shiso",
    "Sumac",
    "Tamarind",
    "Tonka bean",
    "Turmeric",
    "Uzazi",
    "Vanilla",
    "Voatsiperifery",
    "Wasabi",
    "Yuzu",
    "Zedoary",
    "Zereshk",
    "Zest"
  ];

  static List<String> mixtures = [
    "Adjika",
    "Advieh",
    "Baharat",
    "Beau Monde seasoning",
    "Berbere",
    "Bouquet garni",
    "Buknu",
    "Chaat masala",
    "Chaunk",
    "Chili powder",
    "Crab boil",
    "Curry powder",
    "Doubanjiang",
    "Douchi",
    "Duqqa",
    "Fines herbes",
    "Five-spice powder",
    "Garam masala",
    "Garlic powder",
    "Garlic salt",
    "Gochujang",
    "Harissa",
    "Hawaij",
    "Herbes de Provence",
    "Idli podi",
    "Jamaican jerk spice",
    "Khmeli suneli",
    "Lemon pepper",
    "Mitmita",
    "Mixed spice",
    "Montreal steak seasoning",
    "Mulling spices",
    "Old Bay Seasoning",
    "Onion powder",
    "Panch phoron",
    "Persillade",
    "Powder-douce",
    "Pumpkin pie spice",
    "Qâlat daqqa",
    "Quatre épices",
    "Ras el hanout",
    "Recado rojo",
    "Sharena sol",
    "Shichimi",
    "Tabil",
    "Tandoori masala",
    "Vadouvan",
    "Yuzukosho",
    "Za'atar"
  ];

  static List<String> vegetables = [
    "acorn squash",
    "alfalfa sprout",
    "amaranth",
    "anise",
    "artichoke",
    "arugula",
    "asparagus",
    "aubergine",
    "azuki bean",
    "banana squash",
    "basil",
    "bean sprout",
    "beet",
    "black bean",
    "black-eyed pea",
    "bok choy",
    "borlotti bean",
    "broad beans",
    "broccoflower",
    "broccoli",
    "brussels sprout",
    "butternut squash",
    "cabbage",
    "calabrese",
    "caraway",
    "carrot",
    "cauliflower",
    "cayenne pepper",
    "celeriac",
    "celery",
    "chamomile",
    "chard",
    "chayote",
    "chickpea",
    "chives",
    "cilantro",
    "collard green",
    "corn",
    "corn salad",
    "courgette",
    "cucumber",
    "daikon",
    "delicata",
    "dill",
    "eggplant",
    "endive",
    "fennel",
    "fiddlehead",
    "frisee",
    "garlic",
    "gem squash",
    "ginger",
    "green bean",
    "green pepper",
    "habanero",
    "herbs and spice",
    "horseradish",
    "hubbard squash",
    "jalapeno",
    "jerusalem artichoke",
    "jicama",
    "kale",
    "kidney bean",
    "kohlrabi",
    "lavender",
    "leek ",
    "legume",
    "lemon grass",
    "lentils",
    "lettuce",
    "lima bean",
    "mamey",
    "mangetout",
    "marjoram",
    "mung bean",
    "mushroom",
    "mustard green",
    "navy bean",
    "new zealand spinach",
    "nopale",
    "okra",
    "onion",
    "oregano",
    "paprika",
    "parsley",
    "parsnip",
    "patty pan",
    "pea",
    "pinto bean",
    "potato",
    "pumpkin",
    "radicchio",
    "radish",
    "rhubarb",
    "rosemary",
    "runner bean",
    "rutabaga",
    "sage",
    "scallion",
    "shallot",
    "skirret",
    "snap pea",
    "soy bean",
    "spaghetti squash",
    "spinach",
    "squash",
    "sweet potato",
    "tabasco pepper",
    "taro",
    "tat soi",
    "thyme",
    "topinambur",
    "tubers",
    "turnip",
    "wasabi",
    "water chestnut",
    "watercress",
    "white radish",
    "yam",
    "zucchini"
  ];

  static List<String> teas = [
    "88th Night Shincha Organic",
    "Adam's Peak White",
    "Amacha",
    "Amber Oolong",
    "Ancient Green",
    "Anji Bai Cha",
    "Anthemis",
    "Apricot with Flowers",
    "Aracha",
    "Assam GFOP Organic",
    "Assam GFOP",
    "assam",
    "Bai Jiguan",
    "Bai Mudan",
    "Baihao Yinzhen",
    "Baimao Hou",
    "Baker Street Afternoon Blend",
    "Balasun Estate SFTGFOP1 First Flush",
    "Ban Tian Yao",
    "Bancha",
    "Belgachi Special Assam Oolong",
    "Biluochun",
    "Bitter Melon",
    "Black Dragon",
    "Black Label Breakfast Fannings",
    "Black with Vanilla",
    "Black",
    "Blackcurrant",
    "Blue Flower",
    "Bohea Special",
    "Boldo",
    "Bos Ice",
    "Brazilian passion fruit",
    "brown rice",
    "Bu Zhi Chun",
    "Buddha's Palm",
    "Builder's",
    "Butter",
    "Cannabis",
    "Cape Cod Cranberry Fruit",
    "Castleton Estate FTGFOP1 Moonlight",
    "Celestial Tribute",
    "Certified Organic Peppermint",
    "Ceylon English Breakfast",
    "Ceylon Ruhuna BOP1",
    "Ceylon Select",
    "Ceylon Uva OP Organic",
    "Cha Premium Organic",
    "Chai Decaffeinated",
    "Chai Spice",
    "Chai",
    "Chamillo Blend",
    "Chamomile With Lemongrass",
    "Chamomile",
    "Chamraj Estate FOP",
    "Chifir",
    "China Aged",
    "China Black FOP",
    "China Black Pearls",
    "China Chun Mee",
    "China Congou Fannings Organic",
    "China Congou Panyang (Panyong)",
    "China Congou",
    "China Green Decaffeinated",
    "China Green Gyokuro Organic",
    "China Green Mao Jian 'B' Organic",
    "China Green",
    "China Jasmine Da Zhang Organic",
    "China Jasmine",
    "China Keemun First Grade",
    "China Keemun Mao Feng",
    "China Lychee",
    "China Oolong",
    "China Panyang Congou",
    "China Rose Special Chun Mee",
    "China Silver Needle",
    "China Special Green Organic",
    "China Yunnan Organic",
    "China Yunnan Rare Grade",
    "Chinese Herb",
    "Chinese Ornamental Brick",
    "Chinese Sweet",
    "Chiran",
    "Chocolate Earl Grey",
    "Christmas",
    "Chrysanthemum",
    "Chun Mee",
    "Cinnamon Plum Fruit",
    "Cloud",
    "Coca",
    "Coffee Cherry",
    "Coffee",
    "Competition Temomicha Grade A",
    "Compressed",
    "Congou",
    "Constant Comment",
    "Crème Caramel",
    "Crème Vanilla",
    "CTC Fine Assam",
    "CTC Irish Breakfast Blend",
    "Cyclopia",
    "Dafang",
    "Daisajan Estate GFBOP",
    "Dandelion",
    "Darjeeling FTGFOP Special Blend",
    "Darjeeling FTGFOP1",
    "Darjeeling Second Flush BOP Blend",
    "Darjeeling",
    "Darjeeling-Ceylon",
    "Devonshire Earl Grey",
    "Dianhong",
    "Dikom Estate GTGFOP1",
    "Dikom Estate TGFOP1",
    "Dimbula BOP",
    "Dongfang Meiren",
    "Doomni Estate GTGBOP Cl.",
    "Doomni Estate TGFOP1 Cl.",
    "Dragon Phoenix Pearl",
    "Earl Grey Green Decaffeinated",
    "Earl Grey Supreme",
    "Earl Grey with Lavender",
    "Earl Grey",
    "East Frisian BOP",
    "East Frisian TGFOP",
    "East Frisian",
    "Eastern Beauty Oolong",
    "Egyptian Chamomile",
    "English Breakfast",
    "Essiac",
    "Extra Bergamot English Earl Grey",
    "FBOPF Ex. Sp.",
    "Feng Huang Dan Cong Supreme",
    "Fermented",
    "Finest Earl Grey",
    "Finest Russian Caravan",
    "First Grade Gunpowder Green",
    "Flavored",
    "Floral Huang Jin Gui Oolong",
    "Flowering",
    "Fo Shou",
    "Formosa GABA Oolong",
    "Formosa Keemun",
    "Formosa Lapsang Souchong",
    "Formosa Oolong Choicest",
    "Formosa Oolong",
    "Formosa Pouchong",
    "Foucha Imperial Organic",
    "Frances Bissell's Special Blend",
    "Fuding White Cake",
    "Fujian Green Needle",
    "Ganesh Green Assam",
    "Gaoshan",
    "Genmaicha",
    "Ghillidary Estate TGFOP",
    "Golden Monkey",
    "Golden Nepal",
    "Goomtee Estate FTGFOP1 First Flush",
    "Green Extract",
    "Green Fannings Organic",
    "Green Honeybush Organic",
    "Green Ice Cream",
    "Green Rooibos",
    "Green Red Ginseng",
    "Green Tamacha",
    "Green Yerba Maté",
    "Green",
    "Gu Zhang Mao Jian",
    "Guayakí",
    "Gugija Cha",
    "Gunpowder Green Peppermint",
    "Gunpowder Green",
    "Gunpowder",
    "Gynostemma Pentaphyllum",
    "Gyokuro (lit. Jewel Dew)",
    "Gyokuro",
    "Halmari Estate CTC BOP",
    "Halmari Estate GFOP Cl.",
    "Halmari Estate GTGFOP1 Cl.",
    "Halmari Estate TGFBOP1",
    "Halmari Estate TGFOP Cl.",
    "Halmari Estate TGFOP",
    "Halmari Estate TGFOP1",
    "Harishpur Estate TGFBOP",
    "Harmutty Estate GFBOP",
    "Harmutty Estate TGFOP",
    "Hearthside Chai",
    "Heavy-Baked",
    "Heirloom Flowers Organic",
    "Heirloom Yunnan Yellow Buds",
    "Herbal",
    "Herbs and Berries",
    "Heritage Assam Green Spl.",
    "Hibiscus Flowers, Coarse Cut",
    "Hibiscus",
    "Hojicha",
    "Holy Basil Green Leaf Organic",
    "Holy Basil Purple Leaf Organic",
    "Holy Basil",
    "Honey",
    "Hong Kong-style Milk",
    "Hong Tao Keemun",
    "Hua Shan Huang Ya Yellow Buds",
    "Huang Guanyin",
    "Huang Jin Gui Oolong",
    "Huang Meigui",
    "Huang Shan Mao Feng",
    "Huang Shan Sunset",
    "Huang Ya Imperial Yellow",
    "Huangjin Gui",
    "Huangshan Maofeng",
    "Hubei Province Keemun",
    "Hunan Mao Feng",
    "Huoshan Huangya",
    "Hyson",
    "Iced Blend",
    "Iced",
    "Ilex Guayusa",
    "Ilex Kaushue",
    "Imperial",
    "Indonesian Black",
    "Introduction to Fine",
    "Introduction to Oolongs",
    "Irish Breakfast",
    "Iyerpadi Estate BOP",
    "Iyerpadi Estate OP",
    "Jade Cloud Mist",
    "Jade Oolong",
    "Jagertee",
    "Japanese Cherry",
    "Japanese Green GABA (Gabaron)",
    "Japanese Matcha",
    "Japanese Oolong Organic",
    "Japanese Sencha Special Grade",
    "Jasmine Fairy Maiden",
    "Jasmine Imperial",
    "Jasmine Oolong",
    "Jasmine Silver Needles",
    "Jasmine",
    "Java Blend",
    "Java Dewata Estate Silver Tips",
    "Java Malabar Estate OPS",
    "Jin Fo",
    "Jin Jun Mei",
    "Jin Suo Chi",
    "Jin Xuan",
    "Jun Chiyabari Estate Green HP1",
    "Jun Chiyabari Estate HRHT Organic",
    "Junshan Yinzhen",
    "Jūrokucha",
    "Kabusecha",
    "Kagoshima Green",
    "Kagoshima Kabuse Sencha",
    "Kahwah",
    "Kakegawa Matcha Organic",
    "Kakkonto",
    "Kamairicha",
    "Kandy BOP Ceylon",
    "Kandy BOP",
    "Kanyam Estate SFTGFOP1",
    "Karha",
    "Keemun Mao Feng Imperial",
    "Keemun Mao Feng Xiang Luo",
    "Keemun Mao Feng",
    "Keemun Xiang Luo",
    "Keemun",
    "Kenilworth Estate OP",
    "Kenilworth Estate OP1",
    "Kenilworth Estate Pekoe",
    "Kensington Breakfast Blend",
    "Khima Full Moon Delight",
    "Kibena Estate Tanzania BP1",
    "Kombucha",
    "Konacha",
    "Korean Green Sejak Organic",
    "Kuding",
    "Kukicha",
    "Kuzuyu",
    "Kyo Bancha Organic",
    "Labrador",
    "Lady Grey",
    "Lahpet",
    "Lapacho",
    "Lapsang Souchong",
    "Lei Cha",
    "Lemon Grass, Coarse Cut",
    "Lemon Rooibos",
    "Lemon Verbena",
    "Lemon With Ginger",
    "Longjing",
    "Lover's Leap Estate Pekoe 1",
    "Lu'an Melon Seed",
    "Lukwah Estate TGFBOP Spl.",
    "Lumbini Estate FBOPF Ex. Sp.",
    "Lumbini Estate FBOPF Ex. Spl.",
    "Lung Jing Te Ji",
    "Lung-Ching",
    "Mackeypore Estate White Tips",
    "Maghrebi Mint",
    "Magnolia Blossom",
    "Malabar Estate Java OP Clonal",
    "Mangalam Estate FTGFOP1 Cl.",
    "Mango Indica",
    "Maojian",
    "Maracuja/Orange Fruit",
    "Masala Chai",
    "Matcha Bowl",
    "Matcha Scoop",
    "Matcha Whisk",
    "Matcha",
    "Mate Cocido",
    "Mate",
    "Matricaria Chamomilla",
    "Mecha",
    "Meng Ding Huang Ya",
    "Mengding Ganlu",
    "Micromeria Chionistrae",
    "Micromeria Douglasii",
    "Midsummer Dream",
    "Milima Estate Kenya GFOP",
    "Milima Estate Kenya OP",
    "Mincing Lane Breakfast Blend",
    "Misty Mao Feng",
    "Mokalbari East Estate GFBOP",
    "Monk’s Blend",
    "Moon Palace",
    "Moonlight White",
    "Moroccan Green Mint",
    "Mushroom",
    "Mélange de Chamonix",
    "Mélange Noël",
    "Nahorhabi Estate FTGFOP1 Cl.",
    "Namring Estate FTGFOP1 First Flush",
    "Natural Bergamot Earl Grey",
    "Nepali",
    "New England Harvest",
    "New Vithanakande FBOPF Ex. Spl.",
    "Nilgiri Broken Orange Pekoe",
    "Nilgiri",
    "Noon Chai",
    "North Tukvar Estate SFTGFOP",
    "Nuo Mi Ziang",
    "Nuwara Eliya BOP",
    "Oksusucha",
    "Old South Meeting House",
    "Oolong Fannings Organic",
    "Oolong Standard Grade",
    "Oolong",
    "Orange Spice Imperial",
    "Orchid Oolong",
    "Organic Australian Lemon Myrtle",
    "Organic Black Benifuki",
    "Organic China Green Sencha",
    "Organic China Pai Mu Tan",
    "Organic China Sencha",
    "Organic China",
    "Organic English Breakfast",
    "Organic Ginger Root",
    "Organic Green Ceylon OP",
    "Organic Green OP",
    "Organic Gunpowder",
    "Organic Gyokuro",
    "Organic Hunan Black Mao Feng",
    "Organic Jasmine Mao Feng",
    "Organic Jasmine",
    "Organic KUKI Cha GREEN",
    "Organic Leaf",
    "Organic Rooibos",
    "Organic Saiqing",
    "Organic Spearmint",
    "Organic Tamaryokucha",
    "Organic Young Hyson Imperial",
    "Original Earl Grey",
    "Orthodox BOP Darjeeling",
    "Osmanthus Oolong",
    "Pai Mu Tan Select",
    "Pai Mu Tan Special Grade Organic",
    "Pan Long Yin Hao",
    "Panyang Congou Classic",
    "Panyang Congou Select",
    "Panyang Congou Supreme",
    "Panyang Golden Tribute",
    "Panyang Tippy Mao Feng",
    "Peace Iced",
    "Peace",
    "Peach Flavoreds",
    "Peach Melba Fruit",
    "Peppermint",
    "Pi Lo Chun Imperial",
    "Pi Lo Chun",
    "Pinhead Gunpowder",
    "Poire Crème",
    "Pomegranate Magnolia White",
    "Pouchong",
    "Pre-Chingming",
    "Premium China Keemun",
    "Pu-erh",
    "Qilan",
    "Qing Zi You Yun (Lan Xiang)",
    "Qishr",
    "Raspberry Fruit",
    "Red Groats",
    "Rhododendron",
    "Richmond Park Blend",
    "River Shannon Breakfast Blend",
    "Rize",
    "Roasted Barley",
    "Roasted Oolong",
    "Roasted Yerba Maté",
    "Rooibos Apple Cider",
    "Rooibos Candied Almond",
    "Rooibos Vanilla",
    "Rooibos",
    "Rose Congou",
    "Rose Hip",
    "Rose Hips",
    "Roselle",
    "Rougui",
    "Ruanzhi",
    "Russian Caravan",
    "Sacher Blend",
    "Sakurayu",
    "Satispur Estate TGFBOP Spl.",
    "Sayama",
    "Scottish Breakfast Blend",
    "Se Chung Oolong Classic",
    "Season's Pick Keemun",
    "Season's Pick Young Hyson",
    "Sencha Tokujyo Ohashiri",
    "Sencha",
    "Shai Zhen Zhu Shou Mei White Pearls",
    "Shai Zhen Zhu Silver Needle Pearl White",
    "Shincha",
    "Shou Mei Classic",
    "Shoumei",
    "Shui Hsien",
    "Shui Jin Gui",
    "Si Da Ming Cong",
    "Sichuan Zao Bei Jian",
    "Sideritis",
    "Singbulli Estate FOP Exclusive",
    "Spearmint",
    "Special Grade Jasmine",
    "Spring Dragon",
    "St. Isaac’s Blend",
    "St. James Estate BOP",
    "Sticky Rice",
    "Strathdon Estate CTC BP1",
    "Strawberry Cream Fruit",
    "Strawberry/Kiwi Fruit",
    "Sumatra BOP",
    "Summer Blend",
    "Sungnyung",
    "Super Grade",
    "Superfine Keemun",
    "Superior Grade",
    "Suutei Tsai",
    "Sweet Almond Green",
    "Sweet Honey Black",
    "Sweet Orange",
    "Sweet",
    "Söder",
    "Tagetes Lucida",
    "Tai Ping Hou Kui",
    "Taiping Houkui",
    "Tamaryokucha",
    "Tea Bank Estate FBOPF Ex. Sp.",
    "Tea Bank FBOPF Ex. Sp.",
    "Tereré",
    "Thai",
    "Thurbo Estate FTGFOP1 Moonlight",
    "Tibeti",
    "Tie-Guan-Yin",
    "Tieguanyin",
    "Tieluohan",
    "Tindharia FTGFOP1 First Flush",
    "Tippy Orthodox FBOP Assam",
    "Tippy Orthodox GBOP Assam",
    "Tippy Orthodox GFOP Assam",
    "Traditional Masala Chai",
    "Tropical Chai Spice",
    "Tsheringma",
    "Tulsi",
    "Tung-ting",
    "Tuo Cha Organic",
    "Tuo Cha Std.",
    "Tuo Cha, Size 1",
    "Turkish Apple",
    "Turkish Style Blend",
    "Two leaves and a bud",
    "Ukoncha",
    "Uva Special BOP",
    "Vanilla Cream Fruit",
    "Vanilla Honeybush",
    "Vanilla",
    "Victorian Brew BOP1",
    "Vietnam Green Mao Feng Organic",
    "Vietnamese Lotus",
    "Vietnamese",
    "Water Fairy Oolong",
    "Wedang Jahe",
    "White Needle",
    "White",
    "Wong Lo Kat",
    "Wuyi",
    "Xia Sang Ju",
    "Xiang Bi Luo",
    "Yellow",
    "Yerba Buena",
    "Yerba Mate",
    "Yin Jun Mee",
    "Yingdehong",
    "Young Hyson",
    "Yuanyang",
    "Yujacha",
    "Yunnan Black Dragon Pearls",
    "Yunnan Black Snail",
    "Yunnan Fannings Organic",
    "Yunnan FBOP",
    "Yunnan FOP Select",
    "Yunnan GFOP",
    "Yunnan Golden Monkey",
    "Yunnan Green Mao Feng",
    "Yunnan Silver Spiral",
    "Yunnan Silver Tip Mao Feng",
    "Yunnan TGFOP",
    "Yunnan White Needle",
    "Zaloni Estate STGFOP",
    "Zhang Ping Shui Hsian Oolong"
  ];

  static List<String> bread = [
    "bagel",
    "baguette",
    "boule",
    "brioche",
    "casalinga",
    "chapati",
    "ciabatta",
    "cornbread",
    "crumpet",
    "epi",
    "ficelle",
    "flatbread",
    "focaccia",
    "fruit bread",
    "hamburger bun",
    "hardtack",
    "lavash",
    "matzoh",
    "muffin",
    "naan",
    "pain au levain",
    "pain de mie",
    "pane d'olive",
    "paratha",
    "pita",
    "potato bread",
    "pretzel",
    "pumpernickel",
    "roti",
    "rugbrød",
    "rye",
    "scone",
    "soda bread",
    "sourdough",
    "tortilla"
  ];

  static List<String> pastries = [
    "baklava",
    "bomboloni",
    "canelé",
    "cinnamon roll",
    "croissant",
    "cronut",
    "doughnut",
    "éclair",
    "gulab jamun",
    "kouign-amann",
    "mille-feuille",
    "morning bun",
    "pain au chocolat",
    "pastel de nata",
    "profiterole",
    "rugelach",
    "shortcake",
    "stollen",
    "strudel",
    "toaster strudel"
  ];

  static List<String> beers = [
    "aged beer",
    "american rye ale or lager",
    "american-style amber lager",
    "american-style amber/red ale",
    "american-style barley wine ale",
    "american-style brown ale",
    "american-style cream ale or lager",
    "american-style dark lager",
    "american-style ice lager",
    "american-style imperial porter",
    "american-style imperial stout",
    "american-style india black ale",
    "american-style india pale ale",
    "american-style lager",
    "american-style light lager",
    "american-style low-carb light lager",
    "american-style malt liquor",
    "american-style marzen/oktoberfest",
    "american-style pale ale",
    "american-style pilsener",
    "american-style premium lager",
    "american-style sour ale",
    "american-style stout",
    "american-style strong pale ale",
    "american-style wheat wine ale",
    "australasian-style light lager",
    "australasian-style pale ale",
    "baltic-style porter",
    "bamberg-style bock rauchbier",
    "bamberg-style helles rauchbier",
    "bamberg-style marzen",
    "bamberg-style weiss rauchbier",
    "belgian-style blonde ale",
    "belgian-style dark strong ale",
    "belgian-style dubbel",
    "belgian-style flanders/oud bruin",
    "belgian-style fruit lambic",
    "belgian-style gueuze lambic",
    "belgian-style lambic",
    "belgian-style pale ale",
    "belgian-style pale strong ale",
    "belgian-style quadrupel",
    "belgian-style table beer",
    "belgian-style tripel",
    "belgian-style white",
    "berliner-style weisse",
    "bohemian-style pilsener",
    "british-style barley wine ale",
    "british-style imperial stout",
    "brown porter",
    "california common beer",
    "chocolate/cocoa-flavored beer",
    "classic english-style pale ale",
    "classic irish-style dry stout",
    "coffee-flavored beer",
    "dark american wheat ale or lager",
    "dark american-belgo-style ale",
    "dortmunder/european-style export",
    "dry lager",
    "english-style brown ale",
    "english-style dark mild ale",
    "english-style india pale ale",
    "english-style pale mild ale",
    "english-style summer ale",
    "european low-alcohol lager",
    "european-style dark",
    "experimental beer",
    "extra special bitter",
    "field beer",
    "foreign (export)-style stout",
    "french & belgian-style saison",
    "french-style biere de garde",
    "fresh hop ale",
    "fruit beer",
    "fruit wheat ale or lager",
    "german-style brown ale/altbier",
    "german-style doppelbock",
    "german-style eisbock",
    "german-style heller bock/maibock",
    "german-style kolsch",
    "german-style leichtes weizen",
    "german-style marzen",
    "german-style oktoberfest",
    "german-style pilsener",
    "german-style rye ale",
    "german-style schwarzbier",
    "gluten-free beer",
    "golden or blonde ale",
    "herb and spice beer",
    "imperial or double india pale ale",
    "imperial or double red ale",
    "international-style pale ale",
    "international-style pilsener",
    "irish-style red ale",
    "japanese sake-yeast beer",
    "kellerbier - ale",
    "kellerbier - lager",
    "latin american-style light lager",
    "leipzig-style gose",
    "light american wheat ale or lager",
    "munchner-style helles",
    "non-alcoholic beer",
    "oatmeal stout",
    "old ale",
    "ordinary bitter",
    "other belgian-style ales",
    "other strong ale or lager",
    "out of category",
    "pale american-belgo-style ale",
    "porter",
    "pumpkin beer",
    "robust porter",
    "scotch ale",
    "scottish-style export ale",
    "scottish-style heavy ale",
    "scottish-style light ale",
    "session beer",
    "smoke beer",
    "smoke porter",
    "south german-style bernsteinfarbenes weizen",
    "south german-style dunkel weizen",
    "south german-style hefeweizen",
    "south german-style kristal weizen",
    "south german-style weizenbock",
    "special bitter or best bitter",
    "specialty beer",
    "specialty honey lager or ale",
    "specialty stouts",
    "strong ale",
    "sweet stout",
    "traditional german-style bock",
    "tropical-style light lager",
    "vienna-style lager",
    "winter warmer",
    "wood- and barrel-aged beer",
    "wood- and barrel-aged dark beer",
    "wood- and barrel-aged pale to amber beer",
    "wood- and barrel-aged sour beer",
    "wood- and barrel-aged strong beer"
  ];
  static List<Map> items = [
    {'fruit_vegetables': fruits},
    {'herbs': herbs},
    {'spicies': spicies},
    {'mixtures': mixtures},
    {'fruit_vegetables': vegetables},
    {'teas': teas},
    {'bread': bread},
    {'pastries': pastries},
    {'beers_style': beers},
  ];

  static List generateList() {
    List<MyItem> result = [];
    for (var v in items) {
      v.values.first.forEach((j) {
        result.add(new MyItem(name: '$j', type: '${v.keys.first}'));
      });
    }
    return result;
  }

  static MyItem getCategories(_name) {
    List<MyItem> list = generateList();
    return list.firstWhere((item) => item.name == _name);
  }
}

class MyItem {
  String name;
  String type;
  MyItem({this.name, this.type});
}
